version: '3.9'

services:
  backend-service:
    container_name: backend-service
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - backend
    ports:
      - 5080:80
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=root
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root


networks:
  backend:
    external: true
    name: net_secured
