version: '3.9'

services:
  backend:
    container_name: backend_service
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - backend
    ports:
      - 5080:80
    restart: always
    env_file:
      - .env

networks:
  backend:
    external: true
    name: net_secured
